### ISSUE TITLE
Update to Lucia v1.x

### ISSUE THREAD

**Issue by jt196** [huntabyte/sveltekit-lucia-prisma#4]
Some significant changes in v.1x, would you be able to update this? 

I tried myself but can't get my head round it!

**Comment by jt196** [comment]
OK @huntabyte I've opened [a PR](https://github.com/huntabyte/sveltekit-lucia-prisma/pull/5) for the updated code.

**Comment by huntabyte** [comment]
Closed by #5

**Comment by jt196** [comment]
Just a quick, small one, I forgot to update the git link in the Readme.md: 

`git clone https://github.com/jt196/sveltekit-lucia-prisma.git`

Should be:

`git clone https://github.com/huntabyte/sveltekit-lucia-prisma.git`
